server:
    http_listen_port: 3200
    http_listen_address: tempo

distributor:
    receivers:
        zipkin:

storage:
    trace:
        backend: local
        local:
            path: /tmp/tempo/blocks
