global:
    scrape_interval: 2s
    evaluation_interval: 2s

scrape_configs:
    - job_name: 'prometheus'
    - job_name: 'apps'
      metrics_path: '/actuator/prometheus'
      static_configs:
        - targets: ['product-mysql-producer:8082','product-mongodb-consumer:8081','product-kafka-stream:8087','product-rest-server:8088']
